- name: Configure yum repo
  yum_repository:
    name: jenkins
    description: Jenkins YUM repo
    baseurl: "{{ jenkinsYumUrl }}"
    gpgcheck: "{{ jenkinsYumGpgCheck }}"
    gpgkey: "{{ jenkinsYumGpgKey }}"
- name: Ensure {{ jenkinsPackage }} is installed and up to date
  package: name={{ jenkinsPackage }} state=latest
  notify: restart jenkins
- name: Disable setup wizard
  lineinfile:
    path: "{{ jenkinsConfig }}"
    regexp: ^JENKINS_JAVA_OPTIONS=.*
    line: JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
- name: Disable CLI remoting
  copy:
    src: jenkins.CLI.xml
    dest: "{{ jenkinsHome }}/"
    owner: jenkins
    group: jenkins
  notify: restart jenkins
- name: Ensure jenkins is enabled
  service: name={{ jenkinsService }} enabled=yes
- name: Ensure jenkins is started
  service: name={{ jenkinsService }} state=started
  register: jenkins_start_result
- name: Pause for 1 minute if Jenkins has just been started
  pause: minutes=1
  when: jenkins_start_result.changed
- name: Ensure Jenkins is running on port 8080
  wait_for: port=8080 timeout=300
- name: Ensure config.xml is created
  wait_for: path={{ jenkinsHome }}/config.xml
- name: Enable CSRF Protection
  xml:
    path: "{{ jenkinsHome }}/config.xml"
    xpath: "{{ item.xpath }}"
    attribute: "{{ item.attribute }}"
    value: "{{ item.value }}"
  loop:
    - { xpath: /hudson/markupFormatter, attribute: class, value: hudson.markup.EscapedMarkupFormatter }
    - { xpath: /hudson/crumbIssuer, attribute: class, value: hudson.security.csrf.DefaultCrumbIssuer }
    - { xpath: /hudson/crumbIssuer/excludeClientIPFromCrumb, attribute: null, value: "false" }
  notify: restart jenkins
- name: Install plugins
  jenkins_plugin:
    name: "{{ item }}"
    state: present
    url_username: "{{ jenkinsAdminUsername }}"
    url_password: "{{ jenkinsAdminPassword }}"
    with_dependencies: yes
    timeout: 300
  loop: "{{ jenkinsPlugins }}"
  notify: restart jenkins
